variable "asg_max_size" {}
variable "asg_min_size" {}
variable "asg_desired_capacity" {}
variable "availability_zones" {}
variable "launch_template_id" {}
variable "security_group_ids" {}
variable "subnets" {}
variable "port" {}
variable "protocol" {}
variable "vpc_id" {}